module.exports = {
    polishCelebrities: [
        { word: "Robert Lewandowski", hint: "Piłkarz" },
        { word: "Lech Wałęsa", hint: "Były prezydent" },
        { word: "Maria Skłodowska-Curie", hint: "Noblistka" },
        { word: "Fryderyk Chopin", hint: "Kompozytor" },
        { word: "Adam Małysz", hint: "Zimowy sport" },
        { word: "Jan Paweł II", hint: "Papież" },
        { word: "Iga Świątek", hint: "Tenis" },
        { word: "Marcin Gortat", hint: "Koszykarz" },
        { word: "Justyna Kowalczyk", hint: "Narciarka" },
        { word: "Kuba Wojewódzki", hint: "Polski talkshow" },
        { word: "Józef Piłsudski", hint: "Marszałek Polski" },
        { word: "Dawid Podsiadło", hint: "'Małomiasteczkowy'" },
        { word: "Taco Hemingway", hint: "Polski raper" },
        { word: "Zbigniew Boniek", hint: "Były prezes PZPN" },
        { word: "Cezary Pazura", hint: "Polski aktor komediowy" },
        { word: "Mariusz Pudzianowski", hint: "Najpierw dźwigał ciężary, potem rękawice" }
    ],
    worldCelebrities: [
        { word: "Albert Einstein", hint: "Znany fizyk" },
        { word: "Leonardo DiCaprio", hint: "Aktor" },
        { word: "Tom Hanks", hint: "Aktor" },
        { word: "Beyoncé", hint: "Piosenkarka" },
        { word: "Mark Zuckerberg", hint: "Metaverse" },
        { word: "Dwayne Johnson", hint: "WWE" },
        { word: "Cristiano Ronaldo", hint: "Piłkarz" },
        { word: "Grogu", hint: "Mały zielony, smieszny" },
        { word: "Zendaya", hint: "Grała w euforii" },
        { word: "Shakira", hint: "Hips don't lie" },
        { word: "Barack Obama", hint: "Pokojowa nagroda nobla" },
        { word: "Morgan Freeman", hint: "Często kojarzony z głosem narratora" },
        { word: "Lionel Messi", hint: "Piłkarz" },
        { word: "Elon Musk", hint: "Jeden z najbogatszych ludzi na świecie" },
        { word: "Taylor Swift", hint: "Amerykańska piosenkarka" },
        { word: "Keanu Reeves", hint: "Aktor" },
        { word: "Cersei Lannister", hint: "Uprawiałą seks z bratem" },
        { word: "Serena Williams", hint: "Tenis" },
        { word: "Ragnar Lothbrok", hint: "Napadł na Anglię i Francje" },
        { word: "Hulk", hint: "Promieniowanie gamma" },
        { word: "Bill Gates", hint: "Jeden z najbogatszych ludzi na świecie" },
        { word: "Rihanna", hint: "Piosenkarka" },
        { word: "Adele", hint: "Hello" },
        { word: "Scarlett Johansson", hint: "Aktorka" },
        { word: "Brad Pitt", hint: "Aktor" },
        { word: "Angelina Jolie", hint: "Aktorka" },
        { word: "Królowa Elżbieta II", hint: "Nie żyje" },
        { word: "Jeff Bezos", hint: "Jeden z najbogatszych ludzi na świecie" },
        { word: "Stephen Hawking", hint: "Fizyk" },
        { word: "Aang", hint: "Władał wszystkimi żwyiołami" },
        { word: "Ahsoka Tano", hint: "Nie Jedi, ale więcej niż uczennica" },
        { word: "Vladimir Putin", hint: "Zbrodniarz" }
    ],
    tvAndMovieCharacters: [
        { word: "Harry Potter", hint: "Blizna" },
        { word: "Hermiona Granger", hint: "Posiadała amulet cofania czasu" },
        { word: "Ron Weasley", hint: "Ma dużą rodzine" },
        { word: "Luke Skywalker", hint: "Pochodził z tatooine" },
        { word: "Darth Vader", hint: "Zmienił strone" },
        { word: "Indiana Jones", hint: "Archeolog" },
        { word: "James Bond", hint: "Agent" },
        { word: "Katniss Everdeen", hint: "Strzeliła i stała się symbolem"},
        { word: "Sherlock Holmes", hint: "Detektyw" },
        { word: "Walter White", hint: "Chemik" },
        { word: "Voldemort", hint: "Nie ma nosa" },
        { word: "Aragorn", hint: "Król dunedainów" },
        { word: "Legolas", hint: "Strzała w locie i uszy w lesie" },
        { word: "Daenerys Targaryen", hint: "Nie rani ją ogien" },
        { word: "Myszka Miki", hint: "Symbol amerykanskiej animacji" },
        { word: "Simba", hint: "Był w ekipie 3 zwierzat" },
        { word: "Kubuś Puchatek", hint: "Miód jest słodki, a towarzystwo – bardziej" },
        { word: "Jon Snow", hint: "Bękart" },
        { word: "Tyrion Lannister", hint: "Pół-czlowiek" },
        { word: "Tony Stark", hint: "Geniusz, miliarder, playboy" },
        { word: "Kapitan Ameryka", hint: "Miał tarcze" },
        { word: "Wonder Woman", hint: "Superbohaterka" },
        { word: "Joker", hint: "Klaun" },
        { word: "Rick Grimes", hint: "W świecie po apokalipsie prowadzi grupę" },
        { word: "Daryl Dixon", hint: "Kusza i wiatr we włosach" },
        { word: "Batman", hint: "Sierota miliarder" },
        { word: "Spider-Man", hint: "Dobrze sie wspina" },
        { word: "Geralt z Rivii", hint: "Wilk" },
        { word: "Forrest Gump", hint: "Żołnierz idiota" },
        { word: "Rocky Balboa", hint: "Bokser" },
        { word: "Jack Sparrow", hint: "Kapitan" },
        { word: "Han Solo", hint: "Przemytnik z nagrodą i humorem" },
        { word: "Leia Organa", hint: "Przyszłość Rebelii, przeszłość royalsów" },
        { word: "Obi‑Wan Kenobi", hint: "Mistrz w cieniu, mentor w świetle" },
        { word: "Anakin Skywalker", hint: "Przeznaczony, ale łatwo zgarnąć w mrok" },
        { word: "Koziołek Matołek", hint: "Pacanów" },
        { word: "Generał Grevious", hint: "Kolekcjonuje miecze" },
        { word: "Bolek i Lolek", hint: "Dwaj bracia z polskiej kreskówki" },
        { word: "Gandalf", hint: "Czarodziej" },
        { word: "Neo", hint: "Wybrał czerwoną pigułkę i problemy" },
        { word: "Rick Sanchez", hint: "Nienawidzi swojego zięcia" },
        { word: "Morty Smith", hint: "On i jego dziadek są głównymi postaciami" },
        { word: "Frodo Baggins", hint: "Nosił pierścień." },
        { word: "Shrek", hint: "Ma warstwy jak cebula." }
    ],
    everydayItems: [
        { word: "Krzesło", hint: "Służy do siedzenia." }
    ],
    gameItemsAndCharacters: [
        { word: "Mario", hint: "Wąsaty hydraulik" },
        { word: "Luigi", hint: "Jest ubrany na zielono-niebiesko" },
        { word: "Lara Croft", hint: "Pani archeolog" },
        { word: "Kratos", hint: "Zabił wielu bogow" },
        { word: "Pikachu", hint: "Żółty z ogonem" },
        { word: "Sonic", hint: "Szybki jeż" },
        { word: "King Kong", hint: "Duzy goryl" },
        { word: "Creeper", hint: "Wybuchowy potwór" },
        { word: "Ciri", hint: "Popielate włosy." },
        { word: "Yennefer", hint: "Czarodziejka" },
        { word: "Big Smoke", hint: "Postać z Grand Theft Auto" },
        { word: "Jinx", hint: "Wystrzałowa wariatka" },
        { word: "Vi", hint: "Ma metalowe rękawice." },
    ]
};