module.exports = {
    polishCelebrities: [
        { word: "Robert Lewandowski", hint: "Jeden z najlepszych piłkarzy na świecie." },
        { word: "Lech Wałęsa", hint: "Były prezydent, lider Solidarności." },
        { word: "Maria Skłodowska-Curie", hint: "Odkrywczyni dwóch pierwiastków, podwójna noblistka." },
        { word: "Fryderyk Chopin", hint: "Kompozytor i pianista z okresu romantyzmu." },
        { word: "Adam Małysz", hint: "Wybitny polski skoczek narciarski." },
        { word: "Wisława Szymborska", hint: "Polska poetka, laureatka Nagrody Nobla w dziedzinie literatury." },
        { word: "Andrzej Wajda", hint: "Reżyser filmowy, twórca takich filmów jak 'Popiół i diament'." },
        { word: "Jan Paweł II", hint: "Pierwszy papież Polak." },
        { word: "Mikołaj Kopernik", hint: "Astronom, który 'wstrzymał Słońce, ruszył Ziemię'." },
        { word: "Iga Świątek", hint: "Polska tenisistka, liderka światowego rankingu." },
        { word: "Roman Polański", hint: "Reżyser filmowy, twórca takich filmów jak 'Dziecko Rosemary'." },
        { word: "Agnieszka Holland", hint: "Reżyserka filmowa, twórczyni takich filmów jak 'Europa, Europa'." },
        { word: "Marcin Gortat", hint: "Polski koszykarz, grający w NBA." },
        { word: "Monika Brodka", hint: "Polska piosenkarka, laureatka nagrody Fryderyk." },
        { word: "Czesław Miłosz", hint: "Polski poeta, prozaik, eseista, laureat Nagrody Nobla w dziedzinie literatury." },
        { word: "Justyna Kowalczyk", hint: "Polska biegaczka narciarska, medalistka olimpijska." },
        { word: "Jerzy Grotowski", hint: "Polski reżyser teatralny, twórca teatru laboratorium." },
        { word: "Kuba Wojewódzki", hint: "Polski dziennikarz, prezenter telewizyjny." },
        { word: "Tadeusz Kościuszko", hint: "Polski generał, inżynier, architekt, bohater narodowy." },
        { word: "Józef Piłsudski", hint: "Polski polityk, marszałek Polski, naczelny wódz WP." },
        { word: "Jan Matejko", hint: "Polski malarz, twórca takich obrazów jak 'Bitwa pod Grunwaldem'." },
        { word: "Stanisław Lem", hint: "Polski pisarz science fiction, filozof, satyryk." },
        { word: "Dawid Podsiadło", hint: "Polski piosenkarz, laureat nagrody Fryderyk." },
        { word: "Taco Hemingway", hint: "Polski raper, piosenkarz, autor tekstów." },
        { word: "Cezary Pazura", hint: "Polski aktor, reżyser, scenarzysta." },
        { word: "Tomasz Kot", hint: "Polski aktor, reżyser, scenarzysta." },
        { word: "Janusz Gajos", hint: "Polski aktor, reżyser, pedagog." },
        { word: "Krystyna Janda", hint: "Polska aktorka, reżyserka, pedagog." }
    ],
    worldCelebrities: [
        { word: "Albert Einstein", hint: "Twórca teorii względności." },
        { word: "Leonardo da Vinci", hint: "Renesansowy artysta i wynalazca, namalował Mona Lisę." },
        { word: "William Shakespeare", hint: "Angielski dramaturg, autor 'Hamleta'." },
        { word: "Marilyn Monroe", hint: "Ikona kina i symbol seksu lat 50." },
        { word: "Michael Jackson", hint: "Król Popu." },
        { word: "Queen Elizabeth II", hint: "Najdłużej panująca monarchini Wielkiej Brytanii." },
        { word: "Nelson Mandela", hint: "Bojownik o wolność i były prezydent RPA." },
        { word: "Elon Musk", hint: "Przedsiębiorca znany z Tesli i SpaceX." },
        { word: "Oprah Winfrey", hint: "Amerykańska prezenterka telewizyjna i miliarderka." },
        { word: "Tom Hanks", hint: "Aktor znany z ról w 'Forrest Gump' i 'Szeregowiec Ryan'." },
        { word: "Beyoncé", hint: "Amerykańska piosenkarka, aktorka, tancerka." },
        { word: "Dwayne Johnson", hint: "Amerykański aktor, producent, były wrestler." },
        { word: "Cristiano Ronaldo", hint: "Portugalski piłkarz, pięciokrotny zdobywca Złotej Piłki." },
        { word: "Lionel Messi", hint: "Argentyński piłkarz, sześciokrotny zdobywca Złotej Piłki." },
        { word: "Taylor Swift", hint: "Amerykańska piosenkarka, autorka tekstów, multiinstrumentalistka." },
        { word: "Keanu Reeves", hint: "Kanadyjski aktor, muzyk, producent filmowy." },
        { word: "Serena Williams", hint: "Amerykańska tenisistka, 23-krotna mistrzyni wielkoszlemowa." },
        { word: "Bill Gates", hint: "Amerykański przedsiębiorca, filantrop, współzałożyciel Microsoftu." },
        { word: "Rihanna", hint: "Barbadoska piosenkarka, autorka tekstów, aktorka." },
        { word: "Adele", hint: "Brytyjska piosenkarka, autorka tekstów, multiinstrumentalistka." },
        { word: "Scarlett Johansson", hint: "Amerykańska aktorka, producentka filmowa." },
        { word: "Brad Pitt", hint: "Amerykański aktor, producent filmowy." },
        { word: "Angelina Jolie", hint: "Amerykańska aktorka, reżyserka, producentka filmowa." },
        { word: "Jeff Bezos", hint: "Amerykański przedsiębiorca, założyciel Amazona." },
        { word: "Dalai Lama", hint: "Duchowy przywódca Tybetańczyków, laureat Pokojowej Nagrody Nobla." },
        { word: "Stephen Hawking", hint: "Brytyjski fizyk teoretyczny, kosmolog, popularyzator nauki." },
        { word: "Vladimir Putin", hint: "Rosyjski polityk, prezydent Rosji." }
    ],
    tvAndMovieCharacters: [
        { word: "Harry Potter", hint: "Chłopiec, który przeżył." },
        { word: "Hermiona Granger", hint: "Najmądrzejsza czarownica w swoim wieku." },
        { word: "Lord Voldemort", hint: "Ten, którego imienia nie wolno wymawiać." },
        { word: "James Bond", hint: "Agent 007, znany z zamiłowania do Martini." },
        { word: "Indiana Jones", hint: "Archeolog i poszukiwacz przygód z biczem i kapeluszem." },
        { word: "Darth Vader", hint: "Mroczny Lord Sithów, ojciec Luke'a Skywalkera." },
        { word: "Geralt z Rivii", hint: "Wiedźmin, łowca potworów." },
        { word: "Tony Stark (Iron Man)", hint: "Geniusz, miliarder, playboy, filantrop w zbroi." },
        { word: "Joker", hint: "Największy wróg Batmana, znany ze swojego śmiechu." },
        { word: "Homer Simpson", hint: "Głowa rodziny z Springfield, uwielbia pączki." },
        { word: "Luke Skywalker", hint: "Główny bohater Gwiezdnych Wojen, Jedi." },
        { word: "Katniss Everdeen", hint: "Główna bohaterka serii 'Igrzyska Śmierci'." },
        { word: "Sherlock Holmes", hint: "Detektyw z Baker Street, znany z swoich niezwykłych umiejętności obserwacyjnych." },
        { word: "Walter White", hint: "Nauczyciel chemii, który stał się królem narkotykowym." },
        { word: "Daenerys Targaryen", hint: "Królowa Smoków, władcza i piękna." },
        { word: "Jon Snow", hint: "Prawowity król Siedmiu Królestw, członek Nocnej Straży." },
        { word: "Tyrion Lannister", hint: "Karzeł, geniusz, wojownik, członek rodziny Lannisterów." },
        { word: "Michael Scott", hint: "Szef biura, który uwielbia być w centrum uwagi." },
        { word: "Chandler Bing", hint: "Sarkastyczny i zabawny przyjaciel z serialu 'Przyjaciele'." },
        { word: "Kapitan Ameryka", hint: "Superbohater, który walczył przeciwko nazistom podczas II wojny światowej." },
        { word: "Wonder Woman", hint: "Superbohaterka, córka Zeusa, wojowniczka." },
        { word: "Batman", hint: "Mroczny rycerz, który broni Gotham City." },
        { word: "Spider-Man", hint: "Superbohater, który ma nadludzkie zdolności dzięki ugryzieniu pająka." },
        { word: "Forrest Gump", hint: "Człowiek z niskim ilorazem inteligencji, który stał się bohaterem wojennym." },
        { word: "Rocky Balboa", hint: "Bokser, który walczył o mistrzostwo świata." },
        { word: "Kapitan Jack Sparrow", hint: "Pirat, który szukał skarbu i przygód." },
        { word: "Pan Wołodyjowski", hint: "Polski szlachcic, bohater powieści Henryka Sienkiewicza." },
        { word: "Andrzej Kmicic", hint: "Polski szlachcic, bohater powieści Henryka Sienkiewicza." },
        { word: "Zagłoba", hint: "Polski szlachcic, bohater powieści Henryka Sienkiewicza." },
        { word: "Pan Kleks", hint: "Polski nauczyciel, bohater powieści i filmu." },
        { word: "Tytus de Zoo", hint: "Polski chłopiec, bohater powieści i filmu." },
        { word: "Koziołek Matołek", hint: "Polski bohater bajek, znany z swojej mądrości." },
        { word: "Bolek i Lolek", hint: "Polskie bliźniaki, bohaterowie serii filmów animowanych." },
        { word: "Reksio", hint: "Polski pies, bohater serii filmów animowanych." },
        { word: "Ferdynand Kiepski", hint: "Polski bohater bajek, znany z swojej lenistwa." },
        { word: "Hans Kloss", hint: "Polski agent, bohater serialu 'Stawka większa niż życie'." },
        { word: "Janosik", hint: "Słowacki zbójnik, bohater powieści i filmu." },
        { word: "Gandalf", hint: "Czarnoksiężnik, bohater powieści i filmu 'Władca Pierścieni'." },
        { word: "Iron-man", hint: "Superbohater, geniusz, miliarder, filantrop w zbroi." },
        { word: "Rick Sanchez", hint: "Geniusz, wynalazca, podróżnik w czasie." },
        { word: "Morty Sanchez", hint: "Wnuk Ricka, podróżnik w czasie." }
    ],
    everydayItems: [
        "Krzesło",
        "Stół",
        "Lampa",
        "Książka",
        "Długopis",
        "Telefon",
        "Komputer",
        "Okno",
        "Drzwi",
        "Klucze",
        "Buty",
        "Kurtka",
        "Widelec",
        "Nóż",
        "Łyżka",
        "Talerz",
        "Kubek",
        "Zegar",
        "Telewizor",
        "Lodówka",
        "Piekarnik",
        "Pralka",
        "Żelazko",
        "Odkurzacz",
        "Grzebień"
    ],
    gameItemsAndCharacters: [
        { word: "Mario", hint: "Wąsaty hydraulik w czerwonej czapce." },
        { word: "Lara Croft", hint: "Brytyjska archeolog i poszukiwaczka przygód." },
        { word: "Pac-Man", hint: "Żółta kulka zjadająca kropki w labiryncie." },
        { word: "Kratos", hint: "Spartański wojownik, który walczył z bogami." },
        { word: "Pikachu", hint: "Żółty, elektryczny stworek z uniwersum Pokémon." },
        { word: "Creeper (Minecraft)", hint: "Zielony, wybuchowy potwór z popularnej gry w budowanie." },
        { word: "Ciri (Wiedźmin)", hint: "Księżniczka Cintry o popielatych włosach." },
        { word: "Agent 47 (Hitman)", hint: "Łysy zabójca z kodem kreskowym na potylicy." }
    ]
};
