module.exports = {
    polishCelebrities: [
        "Robert Lewandowski",
        "Lech Wałęsa",
        "Iga Świątek",
        "Krzysztof Penderecki",
        "Olga Tokarczuk",
        "Andrzej Wajda",
        "Janusz Gajos",
        "Krystyna Janda",
        "Jerzy Stuhr",
        "Dawid Podsiadło",
        "Taco Hemingway",
        "Marcin Gortat",
        "Joanna Jędrzejczyk",
        "Kuba Wojewódzki",
        "Agnieszka Holland",
        "Cezary Pazura",
        "Tomasz Kot",
        "Magdalena Cielecka",
        "Piotr Adamczyk",
        "Monika Brodka"
    ],
    worldCelebrities: [
        "Albert Einstein",
        "Leonardo DiCaprio",
        "Oprah Winfrey",
        "Tom Hanks",
        "Meryl Streep",
        "Beyoncé",
        "Dwayne Johnson",
        "Cristiano Ronaldo",
        "Lionel Messi",
        "Elon Musk",
        "Taylor Swift",
        "Keanu Reeves",
        "Serena Williams",
        "Bill Gates",
        "Rihanna",
        "Adele",
        "Scarlett Johansson",
        "Brad Pitt",
        "Angelina Jolie",
        "Will Smith",
        "Queen Elizabeth II",
        "Jeff Bezos"
    ],
    tvAndMovieCharacters: [
        "Harry Potter",
        "Hermiona Granger",
        "Ron Weasley",
        "Luke Skywalker",
        "Darth Vader",
        "Indiana Jones",
        "James Bond",
        "Katniss Everdeen",
        "Sherlock Holmes",
        "Walter White",
        "Daenerys Targaryen",
        "Jon Snow",
        "Tyrion Lannister",
        "Michael Scott",
        "Homer Simpson",
        "Tony Stark",
        "Captain America",
        "Wonder Woman",
        "Chandler Bing",
        "The Joker",
        "Batman",
        "Spider-Man",
        "Iron Man",
        "Captain Jack Sparrow",
        "Forrest Gump",
        "Ellen Ripley"
    ]
};
